name: grocery_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_localization: ^0.1.10
  provider: ^6.0.5
  intl_phone_field: ^3.1.0
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.6.2
  country_picker: ^2.0.20
  floating_bottom_navigation_bar: ^1.5.2
  custom_bottom_navigation_bar: ^0.0.1
  pinput: ^2.2.31
  image_picker: ^0.8.7+1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  google_fonts: ^4.0.3
  path_provider: ^2.0.14
  share: ^2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/categories_images/
    - assets/images/grocery_images/
    - assets/images/beverages_images/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/images/Group.png
    - assets/images/Group 1 .png
    - assets/images/8140 1.png
    - assets/images/IMG_20230227_101534.jpg
    - assets/images/banner_background.png
    - assets/images/rise.png
    - assets/images/pulses.png
    - assets/images/banner_image.png
    - assets/flag-united-states_1f1fa-1f1f8.png
    - assets/flag-india_1f1ee-1f1f3.png
    - assets/flag-south-africa_1f1ff-1f1e6.png
    - assets/images/download.jpg
    - assets/images/images.jpg
    - assets/images/images (1).jpg
    - assets/images/download (1).jpg
    - assets/images/images (2).jpg
    - assets/images/images (4).jpg
    - assets/images/download (2).jpg
    - assets/images/download (3).jpg
    - assets/images/download (4).jpg
    - assets/images/download (5).jpg
    - assets/images/images (3).jpg
    - assets/images/download (6).jpg
    - assets/images/download (7).jpg
    - assets/images/download (8).jpg
    - assets/images/download.png
    - assets/images/download (9).jpg
    - assets/1.jpeg
    - assets/2.jpeg
    - assets/3.jpeg
    - assets/shopping-basket-full-variety-grocery-600w-1974727070.webp
    - assets/istockphoto-182175200-612x612.jpg


  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.otf